name: DataBase
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies: 
  mysql1: ^0.17.1
  sqljocky5: ^2.2.1
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
